# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        enabled: true
    serializer:
        serialize_null: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
