nelmio_api_doc:
    documentation:
        info:
            title: Virtual Card App
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/virtual-card
