version:  '3.7'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        expose:
            - '3306'
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - '.apps/main/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - mysql
            - mongodb
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
        user: ${LOCAL_USER}

    mongodb:
        image: mongo
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger
