version:  '3.7'
services:
    mysql:
        image: mysql:5.7
        container_name: virtual_card_mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    nginx:
        image: nginx:1.15.3-alpine
        container_name: virtual_card_nginx
        restart: on-failure
        volumes:
            - './apps/main/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - mysql
            - mongodb
            - redis
            - php
    php:
        container_name: virtual_card_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
        user: ${LOCAL_USER}

    mongodb:
        image: mongo
        container_name: virtual_card_mongo
        restart: on-failure
        command: --storageEngine wiredTiger

    redis:
        image: redis:5.0.6-alpine
        container_name: virtual_card_redis
        restart: on-failure

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - '${ADMINER_PORT}:8080'
