doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            VirtualCard:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'VirtualCard\Entity'
                alias: App
