# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # Just enable service injection in service classes
    # We do not need to keep other classes in our container
    VirtualCard\Service\:
        resource: '../src/Service/*'

    VirtualCard\Vendor\:
        resource: '../src/Vendor/*/Service/*'

    VirtualCard\DataFixtures\:
        resource: '../src/DataFixtures/*'

    VirtualCard\Repository\:
        resource: '../src/Repository/*'

    VirtualCard\Security\:
        resource: '../src/Security/*'

    VirtualCard\EventSubscriber\:
        resource: '../src/EventSubscriber/*'

    VirtualCard\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']

    MongoClient:
        class:  MongoClient
        arguments:
            - "%env(MONGO_URL)%"